config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'hospitals/:hospital_id/appointments/:id/accept', to: 'appointments#accept', as: 'accept_hospital_appointment'
  get 'hospitals/:hospital_id/appointments/:id/reject', to: 'appointments#reject', as: 'reject_hospital_appointment'

  resources :hospitals do
    resources :treatments

    resources :doctors do
      get :add_doctor, :remove_doctor
    end
    resources :assign_treatments do
      get  :remove_treatment
      post :add_treatment
    end
    resources :appointments do
      member do
        put :accept
        put :reject
      end
    end
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'hospitals#index'
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  has_many :hospital_treatments, dependent: :destroy
  has_many :hospitals, through: :hospital_treatments
  has_many :doctor, through: :hospital_treatments
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  def index
    @treatments = Treatment.all
    @hospital = Hospital.find(params[:hospital_id])
  end

  def new
    @treatment = Treatment.new
  end

  def create
    @treatment = Treatment.new(params.require(:treatment).permit(:name, :price))
    respond_to do |format|
      if @treatment.save
        format.html { redirect_to hospital_treatments_path, notice: 'Your project is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @treatment = Treatment.find(params[:id])
  end

  def update
    @treatment = Treatment.find(params[:id])
    respond_to do |format|
      if @treatment.update(params.require(:treatment).permit(:name, :price))
        format.html { redirect_to hospital_treatments_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @treatment  = Treatment.find(params[:id])

    # @bugs=Bug.all
  end

  def destroy
    @treatment  = Treatment.find(params[:id])
    # Destroy/delete the record
    @treatment.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to hospital_treatments_path, notice: 'Record was removed.' }
    end
  end

  #   def hospital_treatment
  #     HospitalTreatment.create!(hospital_id: params[:hospital_id], treatment_id: params[:treatment_id],
  #                               doctor_id: params[:user_id])
  #     debugger
  #     @treatment = Treatment.find(params[:treatment_id])
  #     @hospital = @treatment.hospitals
  #   end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/edit.html.erb
<h1> Edit this Treatment item</h1>
<%= form_for(@treatment, url:"/hospitals/hospital_id/treatments/#{@treatment.id}") do |f| %>
  <div class="form-group row col-md-6 px-5">
    <div class="form-group">
      <%= f.label :name , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :name, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'float-right btn btn-outline-primary'%>
    </div>
  </div>
<% end %>

app/views/treatments/index.html.erb
<h1>Treatments </h1>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>
<%= link_to "Create New Treatment", new_hospital_treatment_path,:class=>"btn btn-secondary mx-5" %>
<table class="table table-lg table-striped ml-4 mx-5 table-bordered" style="max-width: 70rem;">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @treatments.each do |treatment|%>
      <tr class="align-middle">
        <td><%=treatment.name %></td>
        <td class="text-center"><%= link_to "Show", hospital_treatment_path(@hospital.id,treatment.id),:class=>"btn btn-outline-primary" %></td>
        <td class="text-center"><%= link_to "Edit", edit_hospital_treatment_path(@hospital.id,treatment.id),:class=>"btn btn-outline-primary" %></td>
        <td class="text-center"><%= link_to "Delete Treatment Item", hospital_treatment_path(@hospital.id,treatment.id), :class=>"btn btn-outline-primary", data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>
      </tr>
    </tr>
  <% end %>
</tbody>
</table>
<%= link_to "Back", hospitals_path, :class=>"btn btn-outline-primary mx-5"%>

app/views/treatments/new.html.erb
<h1> Create a new Treatment</h1>
<%= form_for(@treatment, url: hospital_treatments_path) do |f| %>
  <% if @treatment.errors.any? %>
    <% @treatment.errors.full_messages.each do |message|%>
      <h3><%= message %></h3>
    <% end %>
  <% end %>
  <div class="form-group row col-md-6 px-5">
    <div class="form-group">
      <%= f.label :name , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :name, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'float-right btn btn-outline-primary'%>
    </div>
  </div>
<% end %>

app/views/treatments/show.html.erb
<h1><%= @treatment.name %></h1>
<p><%= link_to "Back",hospital_treatments_path,:class=>"btn btn-outline-primary"%></p>