config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'hospitals/:hospital_id/appointments/:id/accept', to: 'appointments#accept', as: 'accept_hospital_appointment'
  get 'hospitals/:hospital_id/appointments/:id/reject', to: 'appointments#reject', as: 'reject_hospital_appointment'

  resources :hospitals do
    resources :treatments

    resources :doctors do
      get :add_doctor, :remove_doctor
    end
    resources :assign_treatments do
      get  :remove_treatment
      post :add_treatment
    end
    resources :appointments do
      member do
        put :accept
        put :reject
      end
    end
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'hospitals#index'
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :hospital_treatments, dependent: :destroy
  has_many :treatments, through: :hospital_treatments
  has_many :doctors, through: :hospital_treatments
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    @hospitals = Hospital.all
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new(params.require(:hospital).permit(:name, :city, :address))

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to hospitals_path, notice: 'Your hospital is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
  end

  def update
    @hospital = Hospital.find(params[:id])
    respond_to do |format|
      if @hospital.update(params.require(:hospital).permit(:name, :city, :address))
        format.html { redirect_to hospitals_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @hospital = Hospital.find(params[:id])
    # @bugs = Bug.all.where(project_id: @project.id)
  end

  def destroy
    @hospital = Hospital.find(params[:id])

    @hospital.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to hospitals_path, notice: 'Record was removed.' }
    end
  end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/edit.html.erb
<h1> Edit this Hospital item</h1>
<%= form_for(@hospital) do |f| %>
  <div class="form-group row col-md-6 px-5">
    <div class="form-group">
      <%= f.label :name , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :name, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :city , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :city, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :address , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :address, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'float-right btn btn-outline-primary'%>
    </div>
  </div>
<% end %>

app/views/hospitals/index.html.erb
<h1>Hi,<%=current_user.first_name  if current_user%></h1>
<h2>Welcome to Hospital Management System</h2>
<hr/>
<h1> Hospitals</h1>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>
<% if current_user.Admin?%>
  <%= link_to "Create New Hospital", new_hospital_path,:class=>"btn btn-secondary mx-5" %>
<%end%>
<table class="table table-lg table-striped ml-4 mx-5 table-bordered" style="max-width: 80rem;">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>
    <% @hospitals.each do |hospital|%>
      <tr class="align-middle">
        <td><%=hospital.name %></td>
        <td><%=hospital.city %></td>
        <td><%=hospital.address %></td>
        <td><%if current_user.Admin?%></td>
          <td class="text-center"><%= link_to "Show", hospital_path(hospital),:class=>"btn btn-outline-primary" %></td>
          <td class="text-center"><%= link_to "Edit", edit_hospital_path(hospital),:class=>"btn btn-outline-primary" %></td>
          <td class="text-center"><%= link_to "Delete Hospital Item", hospital_path(hospital) , :class=>"btn btn-outline-primary", data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></td>
          <td><%end%></td>
        <td><%if current_user.Admin? || current_user.Doctor?%></td>
          <td class="text-center"><%= link_to "Treatments", hospital_treatments_path(hospital),:class=>"btn btn-outline-primary"%></td>
          <td><%if current_user.Admin?%></td>
            <td class="text-center"><%= link_to "Assign Doctors", hospital_doctors_path(hospital),:class=>"btn btn-outline-primary"%></td>
            <td><%end%></td>
          <td class="text-center"><%= link_to "Assign Treatment", hospital_assign_treatments_path(hospital),:class=>"btn btn-outline-primary"%></td>
          <td><%end%></td>
        <td class="text-center"><%= link_to "Appointments", hospital_appointments_path(hospital),:class=>"btn btn-outline-primary"%></td>
      </tr>
    </tr>
  <% end %>
</tbody>
</table>

app/views/hospitals/new.html.erb
<h1> Create a new Hospital</h1>
<%= form_for(@hospital) do |f| %>
  <% if @hospital.errors.any? %>
    <% @hospital.errors.full_messages.each do |message|%>
      <h3><%= message %></h3>
    <% end %>
  <% end %>
  <div class="form-group row col-md-6 px-5">
    <div class="form-group">
      <%= f.label :name , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :name, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :city , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :city, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :address , :class=>"col-form-label col-md-1"%>
      <%= f.text_field :address, :class => 'col-md-1 form-control', :required => true %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'float-right btn btn-outline-primary'%>
    </div>
  </div>
<% end %>

app/views/hospitals/show.html.erb
<h1><%= @hospital.name %></h1>
<h1><%= @hospital.city %></h1>
<h1><%= @hospital.address %></h1>
<p><%= link_to "Back",hospitals_path,:class=>"btn btn-outline-primary"%></p>