config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'hospitals/:hospital_id/appointments/:id/accept', to: 'appointments#accept', as: 'accept_hospital_appointment'
  get 'hospitals/:hospital_id/appointments/:id/reject', to: 'appointments#reject', as: 'reject_hospital_appointment'

  resources :hospitals do
    resources :treatments

    resources :doctors do
      get :add_doctor, :remove_doctor
    end
    resources :assign_treatments do
      get  :remove_treatment
      post :add_treatment
    end
    resources :appointments do
      member do
        put :accept
        put :reject
      end
    end
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'hospitals#index'
end

app/controllers/assign_treatments_controller.rb
class AssignTreatmentsController < ApplicationController
  def index
    @hospital = Hospital.find(params[:hospital_id])

    @hospital_treatments = @hospital.hospital_treatments.where.not(treatment_id: nil)
    @doctors = @hospital.doctors.uniq

    @treatment_not_added = Treatment.all.where.not(id: @hospital_treatments.pluck(:treatment_id))
  end

  def add_treatment
    hospital_treatment = HospitalTreatment.find_or_create_by(hospital_id: params[:hospital_id],
                                                             treatment_id: params[:assign_treatment_id], doctor_id: params[:doctor_id])
    hospital_treatment.update(price: params[:price])

    redirect_to hospital_assign_treatments_path, notice: 'Treatment status has been updated.'
  end

  def remove_treatment
    HospitalTreatment.find_by(hospital_id: params[:hospital_id], treatment_id: params[:treatment_id],
                              doctor_id: params[:doctor_id]).destroy
    redirect_to hospital_assign_treatments_path, notice: 'Treatment remove has been updated.'
  end
end

app/views/assign_treatments/index.html.erb
<h1> Treatment Added</h1>
<table class="table table-sm table-striped ml-4" style="max-width: 50rem;">
  <thead>
    <th>Treatment Name</th>
    <th>Assigned Doctor</th>
    <th>Price</th>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @hospital_treatments.each do |hospital_treatment|%>
      <tr>
        <td><%= hospital_treatment.treatment.name %></td>
        <td><%= hospital_treatment.doctor&.name || 'Not assigned' %></td>
        <td><%= hospital_treatment.price %></td>
        <td><%= link_to "Remove from Hospital" , hospital_assign_treatment_remove_treatment_path(@hospital.id, hospital_treatment.id, {doctor_id: hospital_treatment.doctor_id, treatment_id:hospital_treatment.treatment_id}), :class=>"btn btn-outline-primary" %></td>
      <% end%>
    </tbody>
  </table>
  <h1> ALL Treatments </h1>
  <table class="table table-sm table-striped ml-4" style="max-width: 50rem;">
    <thead>
      <th>Treatment Name</th>
      <th>Assign to Doctor</th>
      <tr>
        <th colspan="5"></th>
      </tr>
    </thead>
    <tbody>
      <% @treatment_not_added.each do |treatment|%>
        <tr>
          <td><%= treatment.name %></td>
          <td>
            <%= form_tag(hospital_assign_treatment_add_treatment_path(@hospital.id, treatment.id), method: :post) do %>
              <%= select_tag :doctor_id, options_from_collection_for_select(@doctors, :id, :name), include_blank: true %>
              <%= label_tag :price%>
              <%= text_field_tag :price%>
              <%= submit_tag "Assign to Hospital", class: "btn btn-outline-primary" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </tbody>
</table>
<%= link_to "Back", hospitals_path, :class=>"btn btn-outline-primary mx-5"%>