config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'hospitals/:hospital_id/appointments/:id/accept', to: 'appointments#accept', as: 'accept_hospital_appointment'
  get 'hospitals/:hospital_id/appointments/:id/reject', to: 'appointments#reject', as: 'reject_hospital_appointment'

  resources :hospitals do
    resources :treatments

    resources :doctors do
      get :add_doctor, :remove_doctor
    end
    resources :assign_treatments do
      get  :remove_treatment
      post :add_treatment
    end
    resources :appointments do
      member do
        put :accept
        put :reject
      end
    end
  end

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root to: 'hospitals#index'
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @hospital = Hospital.find(params[:hospital_id])
    @hospital_treatments = @hospital.hospital_treatments.where.not(treatment_id: nil)
    @doctors = @hospital.doctors.uniq
    @appointment_requests = current_user.doctor_requests.includes(:hospital_treatment)
    @treatment_not_added = Treatment.all.where.not(id: @hospital_treatments.pluck(:treatment_id))

    # Requests
    @requests = Request.where(hospital_treatment_id: @hospital_treatments.pluck(:id))
    @request_added = @requests.where(patient_id: current_user.id)
    @request_not_added = @hospital_treatments.where.not(id: @requests.pluck(:hospital_treatment_id))
  end

  def create
    appointment_request = Request.create(patient_id: current_user.id,
                                         hospital_treatment_id: params[:hospital_treatment_id])

    redirect_to hospital_appointments_path, notice: 'Request status has been updated.'
  end

  def destroy
    appointment = Request.find_by(id: params[:id], patient_id: current_user.id).destroy

    redirect_to hospital_appointments_path, notice: 'Request delete has been updated.'
  end

  def appointment_requests
    @appointment_requests = current_user.appointment_requests
  end

  def accept
    appointment_request = Request.find(params[:id])
    appointment_request.accepted!

    redirect_to hospital_appointments_path, notice: 'Appointment request has been accepted.'
  end

  def reject
    appointment_request = Request.find(params[:id])
    appointment_request.rejected!

    redirect_to hospital_appointments_path, notice: 'Appointment request has been rejected.'
  end
end

app/views/appointments/index.html.erb
<% if current_user.Patient? || current_user.Admin?%>
  <h1>Requested Treatments</h1>
  <table class="table table-sm table-striped ml-4" style="max-width: 50rem;">
    <thead>
      <th>Treatment Name</th>
      <th>Doctors</th>
      <th>Price</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @request_added.each do |request| %>
        <tr>
          <td><%= request.hospital_treatment.treatment.name %></td>
          <td><%= request.hospital_treatment.doctor.name%></td>
          <td><%= request.hospital_treatment.price %></td>
          <td>
            <%= button_to 'Cancel Request', hospital_appointment_path(@hospital, request.id), method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h1>Available Treatments</h1>
  <table class="table table-sm table-striped ml-4" style="max-width: 50rem;">
    <thead>
      <th>Treatment Name</th>
      <th>Doctors</th>
      <th>Price</th>
      <th>Action</th>
    </thead>
    <tbody>
      <% @request_not_added.each do |hospital_treatment| %>
        <tr>
          <td><%= hospital_treatment.treatment.name %></td>
          <td><%= hospital_treatment.doctor.name%></td>
          <td><%= hospital_treatment.price %></td>
          <td>
            <%= button_to 'Request Appointment', hospital_appointments_path(@hospital, {hospital_treatment_id:hospital_treatment.id}) ,method: :post, class: 'btn btn-primary' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Back", hospitals_path, :class=>"btn btn-outline-primary mx-5"%>
<%end%>
<% if current_user.Doctor?%>
  <h1>Appointment Requests</h1>
  <table class="table table-sm table-striped ml-4" style="max-width: 50rem;">
    <thead>
      <tr>
        <th>Patient</th>
        <th>Treatment</th>
        <th>Price</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @appointment_requests.each do |appointment_request| %>
        <tr>
          <td><%= appointment_request.patient.name %></td>
          <td><%= appointment_request.hospital_treatment.treatment.name %></td>
          <td><%= appointment_request.hospital_treatment.price %></td>
          <td><%= appointment_request.status %></td>
          <td>
            <% if appointment_request.pending? %>
              <%= link_to 'Accept', accept_hospital_appointment_path(@hospital,appointment_request.id), method: :put, class: 'btn btn-success' %>
              <%= link_to 'Reject', reject_hospital_appointment_path(@hospital,appointment_request.id), method: :put, class: 'btn btn-danger' %>
            <% end %>
          </td>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Back", hospitals_path, :class=>"btn btn-outline-primary mx-5"%>
  <%end%>